services:
  backend_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_dev
    ports:
      - "5000:5000"
    environment:
      - BACKEND_PORT=5000
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydb
    volumes:
      - .:/app
      - backend_dev_nd_modules:/app/node_modules
    networks:
      - myappnetwork
    depends_on:
      - postgres
    
    restart: on-failure
     
  postgres:
    image: postgres:16
    container_name: my-postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - myappnetwork

volumes:
  backend_dev_nd_modules:
  postgresdata:

networks:
  myappnetwork:
    driver: bridge